In [1]:
#Packages related to general operating system & warnings
import os
import warnings
warnings.filterwarnings('ignore')
#Packages related to data importing, manipulation, exploratory data #analysis, data understanding
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from termcolor import colored as cl # text customization
#Packages related to data visualizaiton
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
#Setting plot sizes and type of plot
plt.rc("font", size=14)
plt.rcParams['axes.grid'] = True
plt.figure(figsize=(6,3))
plt.gray()

<Figure size 600x300 with 0 Axes>

In [4]:
!pip uninstall sklearn -y
!pip install Cython
!pip install https://github.com/Santosh-Gupta/scikit-learn/archive/master.zip

     | 6.6 MB 13.1 MB/s 0:00:00
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


In [6]:
from matplotlib.backends.backend_pdf import PdfPages
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn import metrics
from sklearn.impute import MissingIndicator, SimpleImputer
from sklearn.preprocessing import  PolynomialFeatures, KBinsDiscretizer, FunctionTransformer
from sklearn.preprocessing import StandardScaler, MinMaxScaler, MaxAbsScaler
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, LabelBinarizer, OrdinalEncoder
import statsmodels.formula.api as smf
import statsmodels.tsa as tsa
from sklearn.linear_model import LogisticRegression, LinearRegression, ElasticNet, Lasso, Ridge
from sklearn.neighbors import KNeighborsClassifier, KNeighborsRegressor
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor, export_graphviz
from sklearn.ensemble import BaggingClassifier, BaggingRegressor,RandomForestClassifier,RandomForestRegressor
from sklearn.ensemble import GradientBoostingClassifier,GradientBoostingRegressor, AdaBoostClassifier, AdaBoostRegressor
from sklearn.svm import LinearSVC, LinearSVR, SVC, SVR
from xgboost import XGBClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

<h2> Link for the dataset - <a href = "https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud"> Dataset </a>

In [7]:
data=pd.read_csv("creditcard.csv")

In [8]:
Total_transactions = len(data)
normal = len(data[data.Class == 0])
fraudulent = len(data[data.Class == 1])
fraud_percentage = round(fraudulent/normal*100, 2)
print(cl('Total number of Trnsactions are {}'.format(Total_transactions), attrs = ['bold']))
print(cl('Number of Normal Transactions are {}'.format(normal), attrs = ['bold']))
print(cl('Number of fraudulent Transactions are {}'.format(fraudulent), attrs = ['bold']))
print(cl('Percentage of fraud Transactions is {}'.format(fraud_percentage), attrs = ['bold']))

Total number of Trnsactions are 284807
Number of Normal Transactions are 284315
Number of fraudulent Transactions are 492
Percentage of fraud Transactions is 0.17


In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     28

There is no null value in any of the coulmn. So, Feature extraction is not the case. However, PCA can be done and checked if it optimizes the results.

In [14]:
min(data['Amount']), max(data['Amount'])

(0.0, 25691.16)

There is a huge difference between the minimum and maximum amount in transcation. It can drastically deviate the results. That's why it's essential to scal them down usind StandardScaler


In [15]:
sc = StandardScaler()
amount = data['Amount'].values
data['Amount'] = sc.fit_transform(amount.reshape(-1, 1))

Dropping the Time column because it does not affect the transaction being fraudulent

In [16]:
data.drop(['Time'], axis=1, inplace=True)

In [17]:
data.drop_duplicates(inplace=True)

Train-Test split

In [18]:
X = data.drop('Class', axis = 1).values
y = data['Class'].values

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 1)

<h1><b>Model Building



1.   Decision Tree




In [20]:
DT = DecisionTreeClassifier(max_depth = 4, criterion = 'entropy')
DT.fit(X_train, y_train)
dt_yhat = DT.predict(X_test)

In [22]:
print('Accuracy score of the Decision Tree model is {}'.format(accuracy_score(y_test, dt_yhat)))

Accuracy score of the Decision Tree model is 0.9991438853096524


In [23]:
print('Accuracy score of the Decision Tree model is {}'.format(f1_score(y_test, dt_yhat)))

Accuracy score of the Decision Tree model is 0.7489361702127659


In [24]:
confusion_matrix(y_test, dt_yhat, labels = [0, 1])

array([[68769,    19],
       [   40,    88]])



2.   K-nearest neighbors



In [25]:
n = 7
KNN = KNeighborsClassifier(n_neighbors = n)
KNN.fit(X_train, y_train)
knn_yhat = KNN.predict(X_test)

In [26]:
print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, knn_yhat)))

Accuracy score of the K-Nearest Neighbors model is 0.999288989494457


In [27]:
print('F1 score of the K-Nearest Neighbors model is {}'.format(f1_score(y_test, knn_yhat)))

F1 score of the K-Nearest Neighbors model is 0.7949790794979079


In [28]:
confusion_matrix(y_test, knn_yhat, labels = [0, 1])

array([[68772,    16],
       [   33,    95]])



3. Logistic Regression



In [29]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr_yhat = lr.predict(X_test)

In [33]:
print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, lr_yhat)))

Accuracy score of the K-Nearest Neighbors model is 0.9989552498694062


In [34]:
print('F1 score of the K-Nearest Neighbors model is {}'.format(f1_score(y_test, lr_yhat)))

F1 score of the K-Nearest Neighbors model is 0.6666666666666666


In [35]:
confusion_matrix(y_test, lr_yhat, labels = [0, 1])

array([[68772,    16],
       [   56,    72]])



4.   SVM




In [30]:
svm = SVC()
svm.fit(X_train, y_train)
svm_yhat = svm.predict(X_test)

In [36]:
print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, svm_yhat)))

Accuracy score of the K-Nearest Neighbors model is 0.999318010331418


In [37]:
print('F1 score of the K-Nearest Neighbors model is {}'.format(f1_score(y_test, svm_yhat)))

F1 score of the K-Nearest Neighbors model is 0.7813953488372093


In [38]:
confusion_matrix(y_test, svm_yhat, labels = [0, 1])

array([[68785,     3],
       [   44,    84]])



5.   Random Forest



In [31]:
rf = RandomForestClassifier(max_depth = 4)
rf.fit(X_train, y_train)
rf_yhat = rf.predict(X_test)

In [39]:
print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, rf_yhat)))

Accuracy score of the K-Nearest Neighbors model is 0.9991293748911718


In [40]:
print('F1 score of the K-Nearest Neighbors model is {}'.format(f1_score(y_test, rf_yhat)))

F1 score of the K-Nearest Neighbors model is 0.7222222222222223


In [41]:
confusion_matrix(y_test, rf_yhat, labels = [0, 1])

array([[68778,    10],
       [   50,    78]])



6.   XGBoost



In [32]:
xgb = XGBClassifier(max_depth = 4)
xgb.fit(X_train, y_train)
xgb_yhat = xgb.predict(X_test)

In [42]:
print('Accuracy score of the K-Nearest Neighbors model is {}'.format(accuracy_score(y_test, xgb_yhat)))

Accuracy score of the K-Nearest Neighbors model is 0.999506645771664


In [43]:
print('F1 score of the K-Nearest Neighbors model is {}'.format(f1_score(y_test, xgb_yhat)))

F1 score of the K-Nearest Neighbors model is 0.8495575221238937


In [44]:
confusion_matrix(y_test, xgb_yhat, labels = [0, 1])

array([[68786,     2],
       [   32,    96]])

As we can clearly see, out of all the classifiers, XGBoost has the heighest F1 score hence the clear winner in this case.